spring:
  application:
    name: card
    
  jpa:
    generate-ddl: 'true'
    database-platform: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:db_card}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:mysqlPW}
    driver-class-name: com.mysql.cj.jdbc.Driver


management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'


springdoc:
  api-docs:
    version: OPENAPI_3_1


api:
  documentation:
    title: Card API
    description: Card API project for Hyperativa's technical recruitment process
    version: 1.0
    team: 
      name: Hyperativa
      url: http://hyperativa.com.br
      email: email@hyperativa.com.br

app:
  jwtSecret: +kvHAMtKqWhWq0FS6acdfHJLHpLNgqLaZVDWPkfhMzd8b0fTvXs2WoOEWaq65v9alWumkAo0xno+sFIQVWhlew==
  jwtExpirationInMs: 604800000
      
server:
  servlet:
    context-path: /v1/api
  port: '8080'
  
  
logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG
  pattern:
    console: "%clr(TS=){faint}%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z', UTC}){faint}
      [%t] %clr(LEVEL=){faint}%clr(${LOG_LEVEL_PATTERN:%p})
      %clr(TRACEID=){faint}%clr(%X{traceId:-null}){reverse} |
      %clr(CLASS=){faint}%clr(%logger{26}){cyan} |
      %m%n%ex"
